site_name: Data Ingénieurie
site_url: https://pirocheto.github.io/data-engineering-docs/
plugins:
  - privacy
  - search
  # - blog
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
nav:
  - index.md
  - SQL:
    - Démarrage: 
      - Introduction: sql/getting-started/intro.md
      - Installation: sql/getting-started/installation.md
    - Concepts: 
        - Modélisation: sql/concepts/modeling.md
        - Relations: sql/concepts/relashionships.md
    - Langage:
        - Instructions: sql/syntax/instructions.md
        - Functions: sql/syntax/functions.md
    - Ressources: sql/resources.md
theme:
  icon:
    logo: octicons/workflow-16
    repo: fontawesome/brands/git-alt
  language: fr
  name: material
  features:
    - toc.integrate
    - navigation.indexes
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer
  font:
    text: Space Grotesk
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: teal
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pirocheto
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pierre-rochet

  consent:
    title: Cookies
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos
      préférences, ainsi que pour mesurer l'efficacité de notre documentation et
      savoir si les utilisateurs trouvent ce qu'ils cherchent. Avec votre
      consentement, vous nous aidez à améliorer notre documentation.

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
      toc_depth: 3
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://github.com/pirocheto/data-engineering-docs
repo_name: pirocheto/data-engineering-docs
copyright: Copyright &copy; 2025 Pirocheto

extra_css:
  - css/custom.css