site_name: Data Ingénieurie
site_url: https://pirocheto.github.io/data-engineering/
plugins:
  - privacy
  - search
  # - blog
  - git-revision-date-localized:
      type: date
nav:
  - sql.md
  - python.md
theme:
  icon:
    logo: octicons/workflow-16
    repo: fontawesome/brands/git-alt
  language: fr
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.share
    - navigation.footer
  font:
    text: Space Grotesk
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pirocheto
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/pierre-rochet
  consent:
    title: Cookies
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos
      préférences, ainsi que pour mesurer l'efficacité de notre documentation et
      savoir si les utilisateurs trouvent ce qu'ils cherchent. Avec votre
      consentement, vous nous aidez à améliorer notre documentation.

repo_url: https://github.com/pirocheto/data-engineering-docs
repo_name: pirocheto/data-engineering-docs
copyright: Copyright &copy; 2025 Pirocheto